apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-prometheus-service
  namespace: keptn

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptn-create-get-monitoring-namespace
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - update
    resourceNames:
      - "monitoring"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptn-create-prom-clusterrole
rules:
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - get
      - create
      - update
    resourceNames:
      - "prometheus"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptn-prom-prometheus
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - nodes
      - nodes/proxy
      - pods
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "extensions"
    resources:
      - "ingresses"
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs: [ "/metrics" ]
    verbs: [ "get" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-prometheus-service
  namespace: monitoring
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - configmaps
    verbs:
      - get
      - create
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - create
      - update
      - delete
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - create
      - update
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keptn-prometheus-service-get-monitoring-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keptn-create-get-monitoring-namespace
subjects:
  - kind: ServiceAccount
    name: keptn-prometheus-service
    namespace: keptn

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keptn-create-prom-clusterrole
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keptn-create-prom-clusterrole
subjects:
  - kind: ServiceAccount
    name: keptn-prometheus-service
    namespace: keptn
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keptn-prom-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keptn-prom-prometheus
subjects:
  - kind: ServiceAccount
    name: keptn-prometheus-service
    namespace: keptn

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-prometheus-service
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-prometheus-service
subjects:
  - kind: ServiceAccount
    name: keptn-prometheus-service
    namespace: keptn

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-keptndomain-prom-service
  namespace: keptn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-read-keptndomain
subjects:
  - kind: ServiceAccount
    name: keptn-prometheus-service
    namespace: keptn


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: prometheus-service
  replicas: 1
  template:
    metadata:
      labels:
        run: prometheus-service
    spec:
      containers:
        - name: prometheus-service
          image: imrajdas/prometheus-service:ci
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: METRICS_SCRAPE_PATH
              value: '/metrics'
            - name: CONFIGURATION_SERVICE
              value: 'http://configuration-service:8080'
            - name: EVENTBROKER
              value: 'http://localhost:8082/event'
            - name: API
              value: 'ws://api-service:8080/websocket'
            - name: PROMETHEUS_NS
              value: 'monitoring'
            - name: PROMETHEUS_CM
              value: 'prometheus-server-conf'
            - name: PROMETHEUS_LABELS
              value: 'app=prometheus'
            - name: ALERT_MANAGER_CM
              value: 'alertmanager-config'
            - name: ALERT_MANAGER_LABELS
              value: 'app=alertmanager'
            - name: ALERT_MANAGER_NS
              value: 'monitoring'
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
        - name: distributor
          image: keptn/distributor:0.8.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "16Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.event.monitoring.configure'
            - name: PUBSUB_RECIPIENT
              value: '127.0.0.1'
            - name: API_PROXY_PORT
              value: '8082'
      serviceAccountName: keptn-prometheus-service
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: keptn
  labels:
    run: prometheus-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: prometheus-service